source 'https://rubygems.org'
ruby '3.2.2'

gem 'rails', '~> 7.1.0'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 6.0'
gem 'rack-cors'
gem 'bootsnap', require: false
gem 'tzinfo-data', platforms: %i[windows jruby]
